repos:
  - repo: https://github.com/psf/black
    rev: 25.9.0  # black의 버전, 프로젝트에 맞춰 적절히 지정
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0  # ruff-pre-commit의 버전
    hooks:
      - id: ruff
        args: [--fix]  # 린트 에러 자동 수정 옵션