name: Deploy to EC2

on:
  workflow_run:
    workflows: ["Build Docker Image"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 and deploy
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          mkdir -p envs
            # GitHub Secret에 저장해둔 ENV_PROD 내용을 envs/.env.prod 파일로 생성
            printf "%s\n" "${{ secrets.ENV_PROD }}" > envs/.env.prod

          ssh -tt -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $USER@$HOST << EOF
            docker pull $DOCKER_USERNAME/django-app:latest
            docker stop django_container || true
            docker rm django_container || true
            docker run -d --name django_container -p 8000:8000 $DOCKER_USERNAME/django-app:latest
          EOF